version: '3'

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scanner
      - POSTGRES_USER=scanner
      - POSTGRES_PASSWORD=scanner
    container_name: db

  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "1337:1337"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://scanner:scanner@db:5432/scanner
      - POSTGRES_DB=scanner
      - POSTGRES_USER=scanner
      - POSTGRES_PASSWORD=scanner
      - DB_HOST=db

volumes:
  dbdata:

