version: '3'

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scanner
      - POSTGRES_USER=scanner
      - POSTGRES_PASSWORD=scanner
    container_name: db

  web:
    build: .
    command: >
        sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:1337"
    volumes:
      - .:/usr/src/app
    ports:
      - "1337:1337"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://scanner:scanner@db:5432/scanner

volumes:
  dbdata:
