# Generated by Django 4.2.7 on 2023-11-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostReview', '0002_remove_scanresult_services_info_scanresult_kernel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='kernel',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='services_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=12),
        ),
    ]
