# Generated by Django 4.2.7 on 2023-11-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostReview', '0003_remove_scanresult_kernel_scanresult_services_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='services_info',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='kernel',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
