# Generated by Django 4.2.7 on 2023-11-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostReview', '0004_remove_scanresult_services_info_scanresult_kernel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='active_processes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='disk_space',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='firewall_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='groups',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='installed_packages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='memory_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='network_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='sudo_permissions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='sys_logs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='system_load',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='users',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='log',
            field=models.TextField(blank=True),
        ),
    ]
